title: Kevin Stewart's Homepage
page-top-title: What is This?
top-section-bg-text: Computer Science
home-subtitle: BUTTER AND PIE&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
